language: generic
sudo: required
services:
  - docker

install: true

env:
  global:
  - GROUP=fjudith COMMIT=$TRAVIS_COMMIT TAG=$TRAVIS_TAG REPO=bookinfo-load-test;

script:
  - set -e
  # Download istio
  - curl -L https://github.com/istio/istio/releases/download/1.2.5/istio-1.2.5-linux.tar.gz | tar xvzf -
  # Deploy consul
  - pushd istio-1.2.5/install/consul/
  - docker-compose -f istio.yaml up -d
  - popd
  # Deploy Bookinfo
  - pushd istio-1.2.5/samples/bookinfo/platform/consul
  - docker-compose -f bookinfo.yaml up -d
  - popd
  # Buid and run bookinfo-load-test
  - docker build -t ${GROUP}/${REPO}:${COMMIT} .
  - docker run --rm --net consul_istiomesh -t ${GROUP}/${REPO}:${COMMIT} -d 180 -h http://consul_productpage-v1_1:9080 -c 250 -r 60

after_success:
  - set -e;
  - if [ -z "$DOCKER_PASS" ] ; then
      echo "This is a build triggered by an external PR. Skipping docker push.";
      exit 0;
    fi;
  - docker login -u $DOCKER_USER -p $DOCKER_PASS;
  - ./push.sh
