apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: bookinfo
spec:
  rules:
  - http:
      paths:
        - path: "/"
          backend:
            serviceName: productpage
            servicePort: 9080
        - path: "/productpage"
          backend:
            serviceName: productpage
            servicePort: 9080